//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cinemaEntities : DbContext
    {
        public cinemaEntities()
            : base("name=cinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actor> actor { get; set; }
        public virtual DbSet<estudio> estudio { get; set; }
        public virtual DbSet<genero> genero { get; set; }
        public virtual DbSet<nacionalidad> nacionalidad { get; set; }
        public virtual DbSet<director> director { get; set; }
        public virtual DbSet<pelicula> pelicula { get; set; }
    }
}
